CREATE TABLE `ubnt` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `date` datetime DEFAULT CURRENT_TIMESTAMP,
    `model` varchar(255) NOT NULL,
    `name` varchar(255) NOT NULL,
    `mode` varchar(255) NOT NULL,
    `ssid` varchar(255) NOT NULL,
    `security` varchar(255) NOT NULL,
    `version` varchar(255) NOT NULL,
    `uptime` varchar(255) NOT NULL,
    `channel` int NOT NULL,
    `frequency` int NOT NULL,
    `frequency_start` int NOT NULL,
    `frequency_stop` int NOT NULL,
    `distance` float NOT NULL,
    `chains` varchar(255) NOT NULL,
    `txpower` float NOT NULL,
    `antenna` varchar(255) NOT NULL,
    `wlan0_mac` varchar(255) NOT NULL,
    `lan0_mac` varchar(255) NOT NULL,
    `lan0_link` float NOT NULL,
    `ap_mac` varchar(255) NOT NULL,
    `signal_strength` float NOT NULL,
    `signal_horizontal` float NOT NULL,
    `signal_vertical` float NOT NULL,
    `noise_floor` float NOT NULL,
    `ccq` float NOT NULL,
    `txrate` float NOT NULL,
    `rxrate` float NOT NULL,
    `airmax` varchar(255) NOT NULL,
    `priority` varchar(255) NOT NULL,
    `quality` float NOT NULL,
    `capacity` float NOT NULL,
    `wlan0_rx` float NOT NULL,
    `wlan0_tx` float NOT NULL,
    PRIMARY KEY (`id`)
);
